FROM alpine

WORKDIR /app

ENV TZ Asia/Shanghai

# 安装缺失的库
RUN apk add --no-cache libc6-compat

COPY ./go-admin /app/main
COPY ./config/settings.prod.yml /app/config/settings.yml

EXPOSE 8000
RUN chmod +x /app/main
RUN pwd && ls
CMD ["./main","server","-c", "/app/config/settings.yml"]